<a href="https://colab.research.google.com/github/morojuindu4321/cspt_training2026/blob/main/Pandas%26PD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('/content/messy_sales_data.csv')
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.0,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,NaN,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.0,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.0,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,NaN,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.0,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.0,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.0,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.0,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.0,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.0,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.0,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,NaN,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.0,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.0,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,NaN,34.0,Mumbai,2023-06-15,890.0,Clothing,NaN

In [2]:
df.head(6)

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.0,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,NaN,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.0,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.0,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      20 non-null     int64
 1   name             19 non-null     object
 2   age              17 non-null     float64
 3   city             20 non-null     object
 4   signup_date      20 non-null     object
 5   purchase_amount  18 non-null     float64
 6   category         20 non-null     object
 7   email            19 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.4+ KB

In [4]:
df.describe()

       customer_id         age  purchase_amount
count     20.00000   17.000000        18.000000
mean      10.50000   37.352941      2859.444444
std        5.91608   30.985765      5397.086602
min        1.00000   -5.000000       800.000000
25%        5.75000   28.000000       950.000000
50%       10.50000   32.000000      1010.000000
75%       15.25000   38.000000      1175.000000
max       20.00000  150.000000     20000.000000

In [5]:
df.isnull().sum()

customer_id        0
name               1
age                3
city               0
signup_date        0
purchase_amount    2
category           0
email              1
dtype: int64

In [6]:
df.shape

(20, 8)

In [7]:
df.head()

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.0,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,NaN,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.0,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com

In [9]:
df1=df.dropna()
df1

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.0,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
4,5,Sneha Reddy,45.0,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.0,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
7,8,Karan Mehta,38.0,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
9,10,Rohan Gupta,-5.0,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.0,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.0,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.0,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.0,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
15,16,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.0,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.0,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com

In [12]:
df2=df.fillna(1)
df2

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.0,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.0,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,1.0,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.0,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.0,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,1.0,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.0,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.0,Bangalore,2023-03-01,1.0,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.0,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.0,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.0,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.0,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.0,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,1.0,Mumbai,2023-05-05,1.0,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.0,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.0,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.0,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,1,34.0,Mumbai,2023-06-15,890.0,Clothing,1

In [14]:
df2=df.fillna(df['age'].mean())
df2

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.000000,Delhi,2023-01-05,1200.000000,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.000000,Mumbai,05/01/2023,950.000000,electronics,priya.verma@email.com
2,3,Priya Verma,32.000000,Mumbai,05/01/2023,950.000000,electronics,priya.verma@email.com
3,4,Amit Kumar,37.352941,Delhi,2023-01-07,1100.000000,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.000000,Chennai,2023-02-10,15000.000000,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.000000,mumbai,2023-02-15,800.000000,Groceries,vikram.singh@email.com
6,7,Anjali Nair,37.352941,Chennai,15-03-2023,1050.000000,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.000000,Delhi,2023-03-01,990.000000,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.000000,Bangalore,2023-03-01,37.352941,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.000000,Mumbai,2023-03-20,1200.000000,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.000000,Chennai,2023-04-02,875.000000,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.000000,chennai,2023-04-10,1020.000000,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.000000,Delhi,2023-04-15,930.000000,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.000000,Bangalore,2023/05/01,1500.000000,groceries,suresh.babu@email.com
14,15,Kavita Rao,37.352941,Mumbai,2023-05-05,37.352941,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.000000,Delhi,2023-05-12,1010.000000,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.000000,Delhi,2023-05-12,1010.000000,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.000000,Chennai,2023-06-01,995.000000,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.000000,BANGALORE,2023-06-10,20000.000000,Electronics,manoj.tiwari@email.com
19,20,37.352941,34.000000,Mumbai,2023-06-15,890.000000,Clothing,37.352941

In [17]:
df['age']=df['age'].fillna(df['age'].mean())
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.000000,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,37.352941,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.000000,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.000000,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,37.352941,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.000000,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.000000,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.000000,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.000000,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.000000,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.000000,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.000000,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,37.352941,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.000000,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.000000,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,NaN,34.000000,Mumbai,2023-06-15,890.0,Clothing,NaN

In [23]:
df['name']=df['name'].fillna('ACE')
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,25.000000,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,32.000000,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,37.352941,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,45.000000,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,29.000000,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,37.352941,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,38.000000,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,41.000000,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,-5.000000,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,22.000000,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,36.000000,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,150.000000,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,28.000000,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,37.352941,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,31.000000,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,27.000000,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,39.000000,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,tap,34.000000,Mumbai,2023-06-15,890.0,Clothing,NaN

In [24]:
x=df['age'].to_numpy()
x

array([ 25.        ,  32.        ,  32.        ,  37.35294118,
        45.        ,  29.        ,  37.35294118,  38.        ,
        41.        ,  -5.        ,  22.        ,  36.        ,
       150.        ,  28.        ,  37.35294118,  31.        ,
        31.        ,  27.        ,  39.        ,  34.        ])

In [25]:
n=(x-x.min())/(x.max()-x.min())
n

array([0.19354839, 0.23870968, 0.23870968, 0.27324478, 0.32258065,
       0.21935484, 0.27324478, 0.27741935, 0.29677419, 0.        ,
       0.17419355, 0.26451613, 1.        , 0.21290323, 0.27324478,
       0.23225806, 0.23225806, 0.20645161, 0.28387097, 0.2516129 ])

In [26]:
n=(x-x.min())/(x.max()-x.min())
df['age']=n
df

,customer_id,name,age,city,signup_date,purchase_amount,category,email
0,1,Rahul Sharma,0.193548,Delhi,2023-01-05,1200.0,Electronics,rahul.sharma@email.com
1,2,Priya Verma,0.238710,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
2,3,Priya Verma,0.238710,Mumbai,05/01/2023,950.0,electronics,priya.verma@email.com
3,4,Amit Kumar,0.273245,Delhi,2023-01-07,1100.0,Clothing,amit.kumar@email.com
4,5,Sneha Reddy,0.322581,Chennai,2023-02-10,15000.0,Electronics,sneha.reddy@email.com
5,6,Vikram Singh,0.219355,mumbai,2023-02-15,800.0,Groceries,vikram.singh@email.com
6,7,Anjali Nair,0.273245,Chennai,15-03-2023,1050.0,groceries,anjali.nair@email.com
7,8,Karan Mehta,0.277419,Delhi,2023-03-01,990.0,Clothing,karan.mehta@email.com
8,9,Neha Joshi,0.296774,Bangalore,2023-03-01,NaN,Electronics,neha.joshi@email.com
9,10,Rohan Gupta,0.000000,Mumbai,2023-03-20,1200.0,clothing,rohan.gupta@email.com
10,11,Divya Iyer,0.174194,Chennai,2023-04-02,875.0,Groceries,divya.iyer@email.com
11,12,Arjun Rao,0.264516,chennai,2023-04-10,1020.0,Electronics,arjun.rao@email.com
12,13,Meera Pillai,1.000000,Delhi,2023-04-15,930.0,Clothing,meera.pillai@email.com
13,14,Suresh Babu,0.212903,Bangalore,2023/05/01,1500.0,groceries,suresh.babu@email.com
14,15,Kavita Rao,0.273245,Mumbai,2023-05-05,NaN,Electronics,kavita.rao@email.com
15,16,Farhan Ali,0.232258,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
16,17,Farhan Ali,0.232258,Delhi,2023-05-12,1010.0,Clothing,farhan.ali@email.com
17,18,Pooja Nair,0.206452,Chennai,2023-06-01,995.0,groceries,pooja.nair@email.com
18,19,Manoj Tiwari,0.283871,BANGALORE,2023-06-10,20000.0,Electronics,manoj.tiwari@email.com
19,20,tap,0.251613,Mumbai,2023-06-15,890.0,Clothing,NaN